// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUM5I0tYk1wNwO1Z92EjobUy8vrQexsnY',
    appId: '1:1014228853503:web:a02e7eb91b634bb1df62ca',
    messagingSenderId: '1014228853503',
    projectId: 'fir-app-a70d2',
    authDomain: 'fir-app-a70d2.firebaseapp.com',
    storageBucket: 'fir-app-a70d2.firebasestorage.app',
    measurementId: 'G-PYTY41WSET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLxLganxXdq9yaQOKIxchYXRpObNeSKuQ',
    appId: '1:1014228853503:android:fbe244cbf0e66447df62ca',
    messagingSenderId: '1014228853503',
    projectId: 'fir-app-a70d2',
    storageBucket: 'fir-app-a70d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7-z0GPmzKyq593GKzr6Xu_L4d6rKe60',
    appId: '1:1014228853503:ios:485433c9308670e7df62ca',
    messagingSenderId: '1014228853503',
    projectId: 'fir-app-a70d2',
    storageBucket: 'fir-app-a70d2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc7-z0GPmzKyq593GKzr6Xu_L4d6rKe60',
    appId: '1:1014228853503:ios:485433c9308670e7df62ca',
    messagingSenderId: '1014228853503',
    projectId: 'fir-app-a70d2',
    storageBucket: 'fir-app-a70d2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUM5I0tYk1wNwO1Z92EjobUy8vrQexsnY',
    appId: '1:1014228853503:web:8c7f7188b56e8bc9df62ca',
    messagingSenderId: '1014228853503',
    projectId: 'fir-app-a70d2',
    authDomain: 'fir-app-a70d2.firebaseapp.com',
    storageBucket: 'fir-app-a70d2.firebasestorage.app',
    measurementId: 'G-05503TD35E',
  );
}
